#                   
# This source file is part of the Apodini Xpense Example open source project
#
# SPDX-FileCopyrightText: 2018-2021 Paul Schmiedmayer and project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
#
# SPDX-License-Identifier: MIT
#              

branches: [release]
name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: 'Semantic Version Major'
    labels:
      - 'needs version bump'
  - title: 'Semantic Version Minor'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Other Changes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'documentation'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changes

  $CHANGES