name: Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  macosclient:
    name: macOS Client
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: latest
    - name: Check Xcode version
      run: xcodebuild -version
    - name: Check Swift version
      run: swift --version
    - name: Build and test
      run: xcodebuild test -scheme Xpense -destination 'platform=iOS Simulator,OS=15.0,name=iPhone 12'
  linuxarmwebservices:
    name: Linux ARM WebService
    runs-on: ARM64
    container:
      image: ghcr.io/apodini/swift:nightly
    defaults:
      run:
        working-directory: ./WebService
    steps:
    - uses: actions/checkout@v2
    - name: Install libsqlite3
      run: apt-get update && apt-get install -y --no-install-recommends libsqlite3-dev
    - name: Check Swift version
      run: swift --version
    - name: Build and test
      run: swift build
  linuxarmwebservices:
    name: Docker Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./WebService/Dockerfile
          platforms: linux/arm64
  linuxwebservices:
    name: Linux WebService ${{ matrix.linux }}
    runs-on: ubuntu-latest
    container:
      image: swiftlang/swift:nightly-5.5-${{ matrix.linux }}
    strategy:
      matrix:
        linux: [bionic, focal, amazonlinux2, centos8]
    defaults:
      run:
        working-directory: ./WebService
    steps:
    - uses: actions/checkout@v2
    - name: Install libsqlite3
      if: ${{ !(startsWith( matrix.linux, 'centos' ) || startsWith( matrix.linux, 'amazonlinux' )) }}
      run: apt-get update && apt-get install -y --no-install-recommends libsqlite3-dev
    - name: Install libsqlite3
      if: startsWith( matrix.linux, 'amazonlinux' )
      run: yum update -y && yum install -y sqlite-devel
    - name: Install libsqlite3
      if: startsWith( matrix.linux, 'centos' )
      run: yum update -y --nobest && yum install -y sqlite-devel
    - name: Check Swift version
      run: swift --version
    - name: Build and test
      run: swift build -Xswiftc -Xfrontend -Xswiftc -sil-verify-none
