#                   
# This source file is part of the Apodini Xpense Example open source project
# 
# SPDX-FileCopyrightText: 2018-2021 Paul Schmiedmayer and project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
# 
# SPDX-License-Identifier: MIT
# 

name: REUSE Compliance Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  reuse:
    name: REUSE Compliance Check
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
