#                   
# This source file is part of the Apodini Xpense Example open source project
# 
# SPDX-FileCopyrightText: 2018-2021 Paul Schmiedmayer and project authors (see CONTRIBUTORS.md) <paul.schmiedmayer@tum.de>
# 
# SPDX-License-Identifier: MIT
# 

name: Swift Package Update

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:
  
jobs:
  createPR:
    name: Create Pull Request
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: latest
    - name: Check Xcode version
      run: xcodebuild -version
    - name: Check Swift version
      run: swift --version
    - name: Update Swift Packages Gateway
      run: cd ./Shared && swift package update
    - name: Update Swift Packages Database
      run: cd ./WebService && swift package update
    - name: Update Swift Packages Xcode Projekt
      run: |
        rm -f Xpense.xcworkspace/xcshareddata/swiftpm/Package.resolved
        xcodebuild -resolvePackageDependencies
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        commit-message: Update dependencies
        title: Update dependencies
        body: Update the Swift Package dependencies.
        delete-branch: true
        base: develop
        branch: bots/update-dependencies
        assignees: ApodiniBot
        committer: ApodiniBot <ApodiniBot@users.noreply.github.com>
        author: ApodiniBot <ApodiniBot@users.noreply.github.com>
        reviewers: PSchmiedmayer
